$script = <<SCRIPT
  apt update
  sudo apt install python3 python3-pip libpq-dev python-dev -y
  pip3 install psycopg2 Django
SCRIPT

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.provision "shell", inline: $script
  config.vm.provision "file", source: "./script.py", destination: "~/script.py"
end